version: '3'

services:
  n8n:
    image: n8n:latest
    environment:
      - DB_TYPE=sqlite
      - WEBHOOK_TUNNEL_URL=https://your-domain.com
    ports:
      - "5678:5678"
    restart: always
    # volumes раздел удален для совместимости с Timeweb Cloud
    # volumes:
    #   - ./data:/home/node/.n8n
